[project]
name = "zilch-on-terminal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual>=5.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "textual-dev>=1.7.0",
]
